server:
  port: 8083

spring:
  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: localhost
    port: 1025
    username: ecommerce@test.com
    password: 
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

logging:
  level:
    com.lucasgrf.notificationservice: DEBUG
