server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # -----------------------------------------------------------------------
        # User Service Routes
        # -----------------------------------------------------------------------
        - id: user-service-auth-route
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/auth/**, /v3/api-docs/**, /swagger-ui/**, /api-docs/**
            
        - id: user-service-secure-route
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/user/**
          filters:
            - JwtAuthentication

        # -----------------------------------------------------------------------
        # Product Service Routes
        # -----------------------------------------------------------------------
        - id: product-service-route
          uri: ${PRODUCT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/products/**

        - id: product-service-categories-route
          uri: ${PRODUCT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/categories/**

        - id: product-service-stock-route
          uri: ${PRODUCT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/stock/**

        # -----------------------------------------------------------------------
        # Order Service Routes
        # -----------------------------------------------------------------------
        - id: order-service-route
          uri: ${ORDER_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - JwtAuthentication

        - id: order-service-cart-route
          uri: ${ORDER_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - JwtAuthentication

        - id: order-service-payments-route
          uri: ${ORDER_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/payments/**

        # -----------------------------------------------------------------------
        # Notification Service Routes
        # -----------------------------------------------------------------------
        - id: notification-service-route
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - JwtAuthentication

security:
  jwt:
    secret-key: ${JWT_SECRET:mySecretKeyMySecretKeyMySecretKeyMySecretKey}
